/**
 * Flexa Cendekia — Master Data Siswa Resmi (Kondisi Awal / Clean Slate 2026)
 * Basis Data Tahun 2026 (Kode: 26XXXX)
 * 
 * Kondisi Awal:
 * - Belum mengikuti Tes Diagnostik
 * - Belum memilih Cita-Cita
 * - Belum menyusun Roadmap Belajar
 * - Belum mengajukan KRS
 * - Progres: 0%
 */

const FLEXA_STUDENTS_DATA = [
    {
        no: 1,
        nis: '260001',
        nisn: '260001',
        nama: 'Aisha Syahida Amanina',
        jenjang: 'SD',
        kelas: 2,
        email: 'aisha@flexacendekia.com',
        password: 'flexa123',
        citaCita: '',
        gayaBelajar: '',
        statusDiagnostik: 'Belum Tes',
        progres: '0%',
        progresNum: 0,
        roadmapProgress: 0,
        statusKRS: 'Belum Mengisi',
        statusCheckpoint: 'Belum Mulai',
        programStudiTarget: '',
        fakultasTarget: '',
        kodeTautan: 'FLX-AISHA-2601',
        pinTautan: '2601',
        riasec: null,
        targetAkademik: null,
        kehadiran: { hadir: 0, izin: 0, sakit: 0, alpa: 0, total: 0, persentase: 0, status: 'Belum Mulai' }
    },
    {
        no: 2,
        nis: '260002',
        nisn: '260002',
        nama: 'Zuran',
        jenjang: 'SD',
        kelas: 2,
        email: 'zuran@flexacendekia.com',
        password: 'flexa123',
        citaCita: '',
        gayaBelajar: '',
        statusDiagnostik: 'Belum Tes',
        progres: '0%',
        progresNum: 0,
        roadmapProgress: 0,
        statusKRS: 'Belum Mengisi',
        statusCheckpoint: 'Belum Mulai',
        programStudiTarget: '',
        fakultasTarget: '',
        kodeTautan: 'FLX-ZURAN-2602',
        pinTautan: '2602',
        riasec: null,
        targetAkademik: null,
        kehadiran: { hadir: 0, izin: 0, sakit: 0, alpa: 0, total: 0, persentase: 0, status: 'Belum Mulai' }
    },
    {
        no: 3,
        nis: '260003',
        nisn: '260003',
        nama: 'Muhammad Fatih',
        jenjang: 'SD',
        kelas: 4,
        email: 'fatih@flexacendekia.com',
        password: 'flexa123',
        citaCita: '',
        gayaBelajar: '',
        statusDiagnostik: 'Belum Tes',
        progres: '0%',
        progresNum: 0,
        roadmapProgress: 0,
        statusKRS: 'Belum Mengisi',
        statusCheckpoint: 'Belum Mulai',
        programStudiTarget: '',
        fakultasTarget: '',
        kodeTautan: 'FLX-FATIH-2603',
        pinTautan: '2603',
        riasec: null,
        targetAkademik: null,
        kehadiran: { hadir: 0, izin: 0, sakit: 0, alpa: 0, total: 0, persentase: 0, status: 'Belum Mulai' }
    },
    {
        no: 4,
        nis: '260004',
        nisn: '260004',
        nama: 'Danella Adzkia Razani Setiawan',
        jenjang: 'SD',
        kelas: 5,
        email: 'adzkia@flexacendekia.com',
        password: 'flexa123',
        citaCita: '',
        gayaBelajar: '',
        statusDiagnostik: 'Belum Tes',
        progres: '0%',
        progresNum: 0,
        roadmapProgress: 0,
        statusKRS: 'Belum Mengisi',
        statusCheckpoint: 'Belum Mulai',
        programStudiTarget: '',
        fakultasTarget: '',
        kodeTautan: 'FLX-ADZKIA-2604',
        pinTautan: '2604',
        riasec: null,
        targetAkademik: null,
        kehadiran: { hadir: 0, izin: 0, sakit: 0, alpa: 0, total: 0, persentase: 0, status: 'Belum Mulai' }
    },
    {
        no: 5,
        nis: '260005',
        nisn: '260005',
        nama: 'Muhammad Arshaka Afthar Rahma',
        jenjang: 'SMP',
        kelas: 7,
        email: 'arshaka@flexacendekia.com',
        password: 'flexa123',
        citaCita: '',
        gayaBelajar: '',
        statusDiagnostik: 'Belum Tes',
        progres: '0%',
        progresNum: 0,
        roadmapProgress: 0,
        statusKRS: 'Belum Mengisi',
        statusCheckpoint: 'Belum Mulai',
        programStudiTarget: '',
        fakultasTarget: '',
        kodeTautan: 'FLX-ARSHAKA-2605',
        pinTautan: '2605',
        riasec: null,
        targetAkademik: null,
        kehadiran: { hadir: 0, izin: 0, sakit: 0, alpa: 0, total: 0, persentase: 0, status: 'Belum Mulai' }
    },
    {
        no: 6,
        nis: '260006',
        nisn: '260006',
        nama: 'Naura Reihana Nun',
        jenjang: 'SMP',
        kelas: 7,
        email: 'nauranun@flexacendekia.com',
        password: 'flexa123',
        citaCita: '',
        gayaBelajar: '',
        statusDiagnostik: 'Belum Tes',
        progres: '0%',
        progresNum: 0,
        roadmapProgress: 0,
        statusKRS: 'Belum Mengisi',
        statusCheckpoint: 'Belum Mulai',
        programStudiTarget: '',
        fakultasTarget: '',
        kodeTautan: 'FLX-NAURA-2606',
        pinTautan: '2606',
        riasec: null,
        targetAkademik: null,
        kehadiran: { hadir: 0, izin: 0, sakit: 0, alpa: 0, total: 0, persentase: 0, status: 'Belum Mulai' }
    },
    {
        no: 7,
        nis: '260007',
        nisn: '260007',
        nama: 'Muhammad Ega Nabil Manshurin',
        jenjang: 'SMP',
        kelas: 8,
        email: 'nabil@flexacendekia.com',
        password: 'flexa123',
        citaCita: '',
        gayaBelajar: '',
        statusDiagnostik: 'Belum Tes',
        progres: '0%',
        progresNum: 0,
        roadmapProgress: 0,
        statusKRS: 'Belum Mengisi',
        statusCheckpoint: 'Belum Mulai',
        programStudiTarget: '',
        fakultasTarget: '',
        kodeTautan: 'FLX-NABIL-2607',
        pinTautan: '2607',
        riasec: null,
        targetAkademik: null,
        kehadiran: { hadir: 0, izin: 0, sakit: 0, alpa: 0, total: 0, persentase: 0, status: 'Belum Mulai' }
    },
    {
        no: 8,
        nis: '260008',
        nisn: '260008',
        nama: 'Caesar Mutiara Chandra',
        jenjang: 'SMA',
        kelas: 10,
        email: 'caesar12@flexacendekia.com',
        password: 'flexa123',
        citaCita: '',
        gayaBelajar: '',
        statusDiagnostik: 'Belum Tes',
        progres: '0%',
        progresNum: 0,
        roadmapProgress: 0,
        statusKRS: 'Belum Mengisi',
        statusCheckpoint: 'Belum Mulai',
        programStudiTarget: '',
        fakultasTarget: '',
        kodeTautan: 'FLX-CAESAR-2608',
        pinTautan: '2608',
        riasec: null,
        targetAkademik: null,
        kehadiran: { hadir: 0, izin: 0, sakit: 0, alpa: 0, total: 0, persentase: 0, status: 'Belum Mulai' }
    },
    {
        no: 9,
        nis: '260009',
        nisn: '260009',
        nama: 'Aurelia Putri Sujatmiko',
        jenjang: 'SMA',
        kelas: 11,
        email: 'aurelia@flexacendekia.com',
        password: 'flexa123',
        citaCita: '',
        gayaBelajar: '',
        statusDiagnostik: 'Belum Tes',
        progres: '0%',
        progresNum: 0,
        roadmapProgress: 0,
        statusKRS: 'Belum Mengisi',
        statusCheckpoint: 'Belum Mulai',
        programStudiTarget: '',
        fakultasTarget: '',
        kodeTautan: 'FLX-AURELIA-2609',
        pinTautan: '2609',
        riasec: null,
        targetAkademik: null,
        kehadiran: { hadir: 0, izin: 0, sakit: 0, alpa: 0, total: 0, persentase: 0, status: 'Belum Mulai' }
    }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { FLEXA_STUDENTS_DATA };
}
if (typeof window !== 'undefined') {
    window.FLEXA_STUDENTS_DATA = FLEXA_STUDENTS_DATA;
}
