const fs = require('fs');
const path = require('path');

const newCareers = `[
    // Sosial & Hukum
    { id: 'polisi', title: 'Polisi', category: 'Sosial & Hukum', icon: 'local_police', desc: 'Menegakkan hukum dan menjaga ketertiban masyarakat.', img: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?q=80&w=600&auto=format&fit=crop', pt: 'Akademi Kepolisian. Fokus: Hukum, Strategi, & Kepemimpinan.', sma: 'Fokus: PKN, Olahraga, & Sosiologi.', kegiatan: ['Paskibra', 'Pramuka'], quote: '"Melindungi dan mengayomi masyarakat sepenuh hati."' },
    { id: 'tentara', title: 'Tentara', category: 'Sosial & Hukum', icon: 'military_tech', desc: 'Mempertahankan kedaulatan negara dari berbagai ancaman.', img: 'https://images.unsplash.com/photo-1544816155-12df9643f363?q=80&w=600&auto=format&fit=crop', pt: 'Akademi Militer. Fokus: Strategi Militer, Ketahanan, & Kepemimpinan.', sma: 'Fokus: Olahraga, PKN, & Fisika.', kegiatan: ['Paskibra', 'Bela Diri'], quote: '"Mengabdi untuk negara adalah panggilan jiwa tertinggi."' },
    { id: 'hakim', title: 'Hakim', category: 'Sosial & Hukum', icon: 'gavel', desc: 'Memimpin jalannya sidang dan memutuskan perkara.', img: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80&w=600&auto=format&fit=crop', pt: 'S1 Hukum. Fokus: Hukum Pidana/Perdata, Etika Profesi.', sma: 'Fokus: PKN, Bahasa, & Sosiologi.', kegiatan: ['Debat', 'OSIS'], quote: '"Keadilan harus ditegakkan walaupun langit runtuh."' },
    { id: 'pengacara', title: 'Pengacara', category: 'Sosial & Hukum', icon: 'balance', desc: 'Memberikan nasihat hukum dan mewakili klien.', img: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?q=80&w=600&auto=format&fit=crop', pt: 'S1 Hukum. Fokus: Hukum Perdata, Pidana, & Ketatanegaraan.', sma: 'Fokus: PKN, Sosiologi, & Bahasa Indonesia.', kegiatan: ['Debat', 'Moot Court'], quote: '"Hukum adalah perisai bagi yang lemah dan pedang bagi keadilan."' },
    { id: 'diplomat', title: 'Diplomat', category: 'Sosial & Hukum', icon: 'public', desc: 'Mewakili dan melindungi kepentingan negara di luar negeri.', img: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?q=80&w=600&auto=format&fit=crop', pt: 'S1 Hubungan Internasional. Fokus: Diplomasi, Hukum Internasional, & Politik Global.', sma: 'Fokus: Bahasa Asing, Sejarah, & PKN.', kegiatan: ['Model United Nations', 'English Club'], quote: '"Diplomasi adalah seni membangun jembatan antar bangsa."' },
    { id: 'pekerja_sosial', title: 'Pekerja Sosial', category: 'Sosial & Hukum', icon: 'volunteer_activism', desc: 'Membantu individu dan keluarga mengatasi masalah sosial.', img: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?q=80&w=600&auto=format&fit=crop', pt: 'S1 Kesejahteraan Sosial. Fokus: Intervensi Sosial, Advokasi.', sma: 'Fokus: Sosiologi, PKN, & Bahasa.', kegiatan: ['Relawan', 'PMR'], quote: '"Perubahan sosial dimulai dari satu tangan yang terulur."' },

    // Kesehatan
    { id: 'dokter', title: 'Dokter', category: 'Kesehatan', icon: 'stethoscope', desc: 'Mendiagnosis, merawat, dan mencegah penyakit pada manusia.', img: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=600&auto=format&fit=crop', pt: 'S1 Kedokteran. Fokus: Anatomi, Fisiologi, & Patologi Manusia.', sma: 'Fokus: Biologi Medis, Kimia Organik, & Fisika.', kegiatan: ['PMR', 'Olimpiade Biologi'], quote: '"Menyembuhkan satu kehidupan, berarti menjaga kelangsungan umat manusia."' },
    { id: 'perawat', title: 'Perawat', category: 'Kesehatan', icon: 'medical_services', desc: 'Memberikan perawatan dan dukungan kepada pasien.', img: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=600&auto=format&fit=crop', pt: 'S1 Keperawatan. Fokus: Keperawatan Klinik, Komunitas, & Manajemen Pasien.', sma: 'Fokus: Biologi, Kimia, & Kesehatan Masyarakat.', kegiatan: ['PMR', 'Relawan Kesehatan'], quote: '"Perawat adalah jantung dari pelayanan kesehatan yang berkesinambungan."' },
    { id: 'apoteker', title: 'Apoteker', category: 'Kesehatan', icon: 'vaccines', desc: 'Menyiapkan dan mendistribusikan obat-obatan.', img: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?q=80&w=600&auto=format&fit=crop', pt: 'S1 Farmasi. Fokus: Farmakologi, Formulasi Obat, & Kimia Farmasi.', sma: 'Fokus: Kimia, Biologi, & Matematika.', kegiatan: ['Olimpiade Kimia', 'Lab Kimia'], quote: '"Obat yang tepat di tangan yang tepat menyelamatkan nyawa."' },
    { id: 'bidan', title: 'Bidan', category: 'Kesehatan', icon: 'pregnant_woman', desc: 'Membantu proses persalinan dan merawat kesehatan ibu & anak.', img: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?q=80&w=600&auto=format&fit=crop', pt: 'S1 Kebidanan. Fokus: Asuhan Kebidanan, Kesehatan Reproduksi.', sma: 'Fokus: Biologi, Kimia, & Sosiologi.', kegiatan: ['PMR', 'Penyuluhan'], quote: '"Menyambut kehidupan baru dengan kasih sayang dan profesionalisme."' },
    { id: 'ahli_gizi', title: 'Ahli Gizi', category: 'Kesehatan', icon: 'restaurant_menu', desc: 'Memberikan saran tentang diet dan nutrisi sehat.', img: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?q=80&w=600&auto=format&fit=crop', pt: 'S1 Gizi. Fokus: Ilmu Gizi, Dietetika, & Keamanan Pangan.', sma: 'Fokus: Biologi, Kimia, & Kesehatan.', kegiatan: ['UKS', 'Kantin Sehat'], quote: '"Nutrisi yang baik adalah investasi terbaik untuk masa depan."' },
    { id: 'psikolog', title: 'Psikolog', category: 'Kesehatan', icon: 'psychology', desc: 'Mempelajari perilaku dan proses mental manusia.', img: 'https://images.unsplash.com/photo-1573497620053-ea5300f94f21?q=80&w=600&auto=format&fit=crop', pt: 'S1 Psikologi. Fokus: Psikologi Klinis, Sosial, & Perkembangan.', sma: 'Fokus: Sosiologi, Biologi, & Bahasa.', kegiatan: ['Konseling Sebaya', 'Debat'], quote: '"Memahami pikiran manusia adalah kunci untuk membangun masyarakat yang sehat."' },

    // Pendidikan
    { id: 'guru', title: 'Guru', category: 'Pendidikan', icon: 'school', desc: 'Mendidik dan membimbing siswa di sekolah.', img: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=600&auto=format&fit=crop', pt: 'S1 Pendidikan. Fokus: Pedagogi, Kurikulum, & Psikologi Pendidikan.', sma: 'Fokus: Mata pelajaran pilihan, Bahasa, & Sosiologi.', kegiatan: ['Tutor Sebaya', 'OSIS'], quote: '"Guru yang hebat menginspirasi muridnya untuk melampaui batas kemampuan diri."' },
    { id: 'dosen', title: 'Dosen', category: 'Pendidikan', icon: 'local_library', desc: 'Mengajar dan melakukan penelitian di universitas.', img: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?q=80&w=600&auto=format&fit=crop', pt: 'S2/S3 Bidang Ilmu. Fokus: Riset, Publikasi, & Pengajaran Tinggi.', sma: 'Fokus: Bidang minat akademik, Riset, & Penulisan.', kegiatan: ['Karya Ilmiah', 'Debat Ilmiah'], quote: '"Dosen bukan hanya pengajar, tapi juga pencipta pengetahuan baru."' },
    { id: 'ustadz', title: 'Ustad/Ustadzah', category: 'Pendidikan', icon: 'menu_book', desc: 'Mengajarkan ilmu agama dan membina akhlak.', img: 'https://images.unsplash.com/photo-1609599006353-e629aaabfeae?q=80&w=600&auto=format&fit=crop', pt: 'S1 Pendidikan Agama / Tarbiyah. Fokus: Ilmu Agama, Pedagogi Islam.', sma: 'Fokus: Agama, Sejarah, & Bahasa Arab.', kegiatan: ['Rohis', 'Dakwah Sekolah'], quote: '"Membangun karakter bangsa dengan fondasi iman yang kuat."' },
    { id: 'kepala_sekolah', title: 'Kepala Sekolah', category: 'Pendidikan', icon: 'admin_panel_settings', desc: 'Memimpin dan memanajemen operasional sebuah sekolah.', img: 'https://images.unsplash.com/photo-1577896851231-70ef18881754?q=80&w=600&auto=format&fit=crop', pt: 'S2 Manajemen Pendidikan. Fokus: Kepemimpinan, Kebijakan Sekolah.', sma: 'Fokus: Sosiologi, Ekonomi, & Bahasa.', kegiatan: ['OSIS', 'Organisasi'], quote: '"Kepemimpinan yang baik menciptakan lingkungan belajar yang optimal."' },
    { id: 'pustakawan', title: 'Pustakawan', category: 'Pendidikan', icon: 'library_books', desc: 'Mengelola perpustakaan dan sistem informasi.', img: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?q=80&w=600&auto=format&fit=crop', pt: 'S1 Ilmu Perpustakaan. Fokus: Manajemen Informasi, Arsip, & Literasi.', sma: 'Fokus: Bahasa, TIK, & Sosiologi.', kegiatan: ['Klub Buku', 'Majalah Sekolah'], quote: '"Perpustakaan adalah gerbang menuju pengetahuan tak terbatas."' },
    
    // Sains & Teknologi
    { id: 'programmer', title: 'Programmer', category: 'Sains & Teknologi', icon: 'code', desc: 'Menulis dan menguji kode untuk perangkat lunak.', img: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=600&auto=format&fit=crop', pt: 'S1 Teknik Informatika. Fokus: Algoritma, Rekayasa Perangkat Lunak, & Basis Data.', sma: 'Fokus: Matematika, Logika Komputasi, & Bahasa Inggris.', kegiatan: ['Klub Coding', 'OSN Komputer'], quote: '"Kode yang baik adalah puisi yang dapat dijalankan oleh mesin."' },
    { id: 'data_scientist', title: 'Data Scientist', category: 'Sains & Teknologi', icon: 'query_stats', desc: 'Mengolah pola data besar, statistik, dan machine learning.', img: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=600&auto=format&fit=crop', pt: 'S1 Ilmu Komputer / Sains Data. Fokus: Machine Learning, Big Data, & Statistika Terapan.', sma: 'Fokus: Matematika Lanjut, Pemrograman Dasar, & Probabilitas.', kegiatan: ['Klub Coding', 'Karya Ilmiah Remaja'], quote: '"Data adalah minyak baru, namun insight adalah energi penggeraknya."' },
    { id: 'peneliti_sains', title: 'Peneliti Sains', category: 'Sains & Teknologi', icon: 'science', desc: 'Melakukan eksperimen untuk penemuan ilmiah baru.', img: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?q=80&w=600&auto=format&fit=crop', pt: 'S1/S2 Biologi/Fisika/Kimia. Fokus: Metodologi Riset, Analisis Eksperimental.', sma: 'Fokus: Sains (Fis/Kim/Bio), Matematika.', kegiatan: ['Karya Ilmiah Remaja', 'Lab Sekolah'], quote: '"Setiap eksperimen adalah langkah mendekati kebenaran alam."' },
    { id: 'insinyur', title: 'Insinyur', category: 'Sains & Teknologi', icon: 'engineering', desc: 'Merancang dan membangun mesin, sistem, atau struktur.', img: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?q=80&w=600&auto=format&fit=crop', pt: 'S1 Teknik Mesin/Sipil. Fokus: Mekanika, Termodinamika, & Material.', sma: 'Fokus: Fisika, Matematika Lanjut, & Kimia.', kegiatan: ['Olimpiade Fisika', 'Klub Robotik'], quote: '"Insinyur mengubah ilmu pengetahuan menjadi solusi nyata bagi kehidupan."' },
    { id: 'teknisi', title: 'Teknisi', category: 'Sains & Teknologi', icon: 'build', desc: 'Memperbaiki dan memelihara peralatan teknis/elektronik.', img: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?q=80&w=600&auto=format&fit=crop', pt: 'D3/S1 Vokasi. Fokus: Praktik Elektro/Mesin, Trouble-shooting.', sma: 'Fokus: Fisika, Keterampilan Praktis, TIK.', kegiatan: ['Klub Robotik', 'Prakarya'], quote: '"Keterampilan teknis memastikan dunia tetap berputar."' },

    // Kreatif
    { id: 'desainer_grafis', title: 'Desainer Grafis', category: 'Kreatif', icon: 'brush', desc: 'Menciptakan konsep visual menggunakan perangkat lunak komputer.', img: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=600&auto=format&fit=crop', pt: 'S1 Desain Komunikasi Visual. Fokus: Tipografi, Branding, & Ilustrasi Digital.', sma: 'Fokus: Seni Rupa, TIK, & Bahasa Inggris.', kegiatan: ['Klub Desain', 'Mading Kreatif'], quote: '"Desain yang baik adalah invisible — ia bekerja tanpa harus meminta perhatian."' },
    { id: 'fotografer', title: 'Fotografer', category: 'Kreatif', icon: 'photo_camera', desc: 'Mengambil gambar profesional untuk berbagai keperluan.', img: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?q=80&w=600&auto=format&fit=crop', pt: 'S1 Fotografi / DKV. Fokus: Teknik Kamera, Komposisi, & Post-Processing.', sma: 'Fokus: Seni Rupa, TIK, & Fisika (Optik).', kegiatan: ['Klub Fotografi', 'Jurnalistik'], quote: '"Setiap foto menceritakan kisah yang tak bisa diungkapkan oleh kata-kata."' },
    { id: 'penulis', title: 'Penulis', category: 'Kreatif', icon: 'edit', desc: 'Menciptakan karya tulis seperti buku, artikel, atau naskah.', img: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?q=80&w=600&auto=format&fit=crop', pt: 'S1 Sastra / Komunikasi. Fokus: Penulisan Kreatif, Jurnalisme, & Linguistik.', sma: 'Fokus: Bahasa Indonesia, Bahasa Inggris, & Sosiologi.', kegiatan: ['Majalah Sekolah', 'Lomba Cerpen'], quote: '"Kata-kata yang tepat memiliki kekuatan untuk mengubah dunia."' },
    { id: 'musisi', title: 'Musisi', category: 'Kreatif', icon: 'music_note', desc: 'Menciptakan dan menampilkan musik.', img: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?q=80&w=600&auto=format&fit=crop', pt: 'S1 Musik. Fokus: Teori Musik, Komposisi, & Performance.', sma: 'Fokus: Seni Musik, Bahasa, & Matematika.', kegiatan: ['Band Sekolah', 'Paduan Suara'], quote: '"Musik adalah bahasa universal yang menyentuh jiwa tanpa kata."' },
    { id: 'animator', title: 'Animator', category: 'Kreatif', icon: 'animation', desc: 'Menciptakan gambar bergerak untuk film atau permainan.', img: 'https://images.unsplash.com/photo-1535016120720-40c646be5580?q=80&w=600&auto=format&fit=crop', pt: 'S1 Animasi / DKV. Fokus: Animasi 2D/3D, Storyboarding, & Motion Graphics.', sma: 'Fokus: Seni Rupa, Matematika, & TIK.', kegiatan: ['Klub Film', 'Lomba Animasi'], quote: '"Animasi memberi kehidupan pada imajinasi dan menghidupkan cerita."' },

    // Bisnis
    { id: 'akuntan', title: 'Akuntan', category: 'Bisnis', icon: 'account_balance', desc: 'Mengelola, menganalisis, dan melaporkan keuangan.', img: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=600&auto=format&fit=crop', pt: 'S1 Akuntansi. Fokus: Akuntansi Keuangan, Audit, & Perpajakan.', sma: 'Fokus: Ekonomi, Akuntansi Dasar, & Matematika Bisnis.', kegiatan: ['Koperasi Siswa', 'Olimpiade Ekonomi'], quote: '"Kesehatan finansial adalah cermin dari keberhasilan sebuah strategi."' },
    { id: 'marketing', title: 'Marketing', category: 'Bisnis', icon: 'campaign', desc: 'Merencanakan kampanye promosi dan strategi pemasaran.', img: 'https://images.unsplash.com/photo-1533750516457-a7f992034fec?q=80&w=600&auto=format&fit=crop', pt: 'S1 Manajemen Pemasaran. Fokus: Perilaku Konsumen, Strategi Promosi.', sma: 'Fokus: Ekonomi, Sosiologi, Bahasa.', kegiatan: ['Bazar Sekolah', 'Klub Kewirausahaan'], quote: '"Pemasaran yang hebat tidak terasa seperti pemasaran."' },
    { id: 'wirausaha', title: 'Wirausaha', category: 'Bisnis', icon: 'store', desc: 'Mendirikan dan mengelola bisnis mandiri.', img: 'https://images.unsplash.com/photo-1556761175-4b46a572b786?q=80&w=600&auto=format&fit=crop', pt: 'S1 Bisnis/Kewirausahaan. Fokus: Strategi Bisnis, Inovasi, Manajemen.', sma: 'Fokus: Ekonomi, TIK, Sosiologi.', kegiatan: ['Kewirausahaan', 'OSIS'], quote: '"Pengusaha melihat peluang di mana orang lain melihat hambatan."' },
    { id: 'analis_keuangan', title: 'Analis Keuangan', category: 'Bisnis', icon: 'trending_up', desc: 'Menganalisis data keuangan untuk keputusan investasi.', img: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop', pt: 'S1 Manajemen Keuangan. Fokus: Portofolio, Risiko Keuangan.', sma: 'Fokus: Ekonomi, Matematika, Statistik.', kegiatan: ['Olimpiade Ekonomi', 'Koperasi'], quote: '"Angka menceritakan cerita yang tak pernah bohong."' },
    { id: 'hrd', title: 'HR', category: 'Bisnis', icon: 'groups', desc: 'Mengelola sumber daya manusia di perusahaan.', img: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=600&auto=format&fit=crop', pt: 'S1 Psikologi / Manajemen SDM. Fokus: Rekrutmen, Pengembangan Pegawai.', sma: 'Fokus: Sosiologi, Psikologi, Bahasa.', kegiatan: ['OSIS', 'Organisasi'], quote: '"Aset paling berharga dari sebuah perusahaan adalah karyawannya."' },

    // Olahraga & Seni
    { id: 'atlet', title: 'Atlet', category: 'Olahraga & Seni', icon: 'sports_gymnastics', desc: 'Berkompetisi dalam acara olahraga profesional.', img: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?q=80&w=600&auto=format&fit=crop', pt: 'S1 Ilmu Keolahragaan / Pelatihan. Fokus: Fisiologi Olahraga, Biomekanika, & Nutrisi Atlet.', sma: 'Fokus: Olahraga, Biologi, & Bahasa.', kegiatan: ['Tim Olahraga', 'Kejuaraan Daerah'], quote: '"Kemenangan bukanlah segalanya, tetapi keinginan untuk menang adalah segalanya."' },
    { id: 'pelatih', title: 'Pelatih', category: 'Olahraga & Seni', icon: 'sports', desc: 'Melatih dan mengarahkan atlet atau tim olahraga.', img: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?q=80&w=600&auto=format&fit=crop', pt: 'S1 Pendidikan Olahraga / Kepelatihan. Fokus: Metodologi Latihan, Strategi, & Psikologi Sport.', sma: 'Fokus: Olahraga, Biologi, & Kepemimpinan.', kegiatan: ['Tim Olahraga', 'Asisten Pelatih'], quote: '"Pelatih hebat mencetak juara, bukan hanya di lapangan tapi juga dalam kehidupan."' },
    { id: 'pelukis', title: 'Pelukis', category: 'Olahraga & Seni', icon: 'palette', desc: 'Menciptakan karya seni rupa menggunakan berbagai media.', img: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?q=80&w=600&auto=format&fit=crop', pt: 'S1 Seni Rupa. Fokus: Teknik Lukis, Sejarah Seni, Estetika.', sma: 'Fokus: Seni Budaya, Sejarah.', kegiatan: ['Pameran Seni', 'Klub Melukis'], quote: '"Setiap kanvas adalah cermin dari jiwa pelukisnya."' },
    { id: 'penari', title: 'Penari', category: 'Olahraga & Seni', icon: 'accessibility_new', desc: 'Mengekspresikan cerita dan emosi melalui gerakan tubuh.', img: 'https://images.unsplash.com/photo-1547153760-18fc86324498?q=80&w=600&auto=format&fit=crop', pt: 'S1 Seni Tari. Fokus: Koreografi, Sejarah Tari, Ekspresi Tubuh.', sma: 'Fokus: Seni Budaya, Olahraga.', kegiatan: ['Klub Tari', 'Festival Budaya'], quote: '"Tarian adalah puisi tersembunyi dari jiwa."' },
    { id: 'aktor', title: 'Aktor', category: 'Olahraga & Seni', icon: 'theater_comedy', desc: 'Memerankan karakter dalam pertunjukan atau film.', img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600&auto=format&fit=crop', pt: 'S1 Seni Peran / Teater. Fokus: Akting, Penyutradaraan, & Dramaturgi.', sma: 'Fokus: Seni Budaya, Bahasa, & Sosiologi.', kegiatan: ['Teater Sekolah', 'Klub Drama'], quote: '"Seni peran adalah cermin kehidupan yang membantu kita memahami diri sendiri."' }
]`;

const newFilterHTML = `
<button class="filter-btn px-4 py-2 bg-primary text-white ledger-border text-[12px] font-medium transition-all" data-category="Semua">Semua</button>
<button class="filter-btn px-4 py-2 bg-white ledger-border text-[12px] font-medium hover:bg-primary hover:text-white transition-all" data-category="Sosial & Hukum">Sosial & Hukum</button>
<button class="filter-btn px-4 py-2 bg-white ledger-border text-[12px] font-medium hover:bg-primary hover:text-white transition-all" data-category="Kesehatan">Kesehatan</button>
<button class="filter-btn px-4 py-2 bg-white ledger-border text-[12px] font-medium hover:bg-primary hover:text-white transition-all" data-category="Pendidikan">Pendidikan</button>
<button class="filter-btn px-4 py-2 bg-white ledger-border text-[12px] font-medium hover:bg-primary hover:text-white transition-all" data-category="Sains & Teknologi">Sains & Teknologi</button>
<button class="filter-btn px-4 py-2 bg-white ledger-border text-[12px] font-medium hover:bg-primary hover:text-white transition-all" data-category="Kreatif">Kreatif</button>
<button class="filter-btn px-4 py-2 bg-white ledger-border text-[12px] font-medium hover:bg-primary hover:text-white transition-all" data-category="Bisnis">Bisnis</button>
<button class="filter-btn px-4 py-2 bg-white ledger-border text-[12px] font-medium hover:bg-primary hover:text-white transition-all" data-category="Olahraga & Seni">Olahraga & Seni</button>
`.trim();

function replaceInFile(filepath, targetArrayRegex, replaceContent) {
    if (fs.existsSync(filepath)) {
        let content = fs.readFileSync(filepath, 'utf8');
        content = content.replace(targetArrayRegex, replaceContent);
        fs.writeFileSync(filepath, content);
        console.log('Updated ' + filepath);
    }
}

// 1. Update 05_pilih-cita-cita/code.html
const file05 = path.join(__dirname, '05_pilih-cita-cita', 'code.html');
if (fs.existsSync(file05)) {
    let htmlContent = fs.readFileSync(file05, 'utf8');
    // replace array
    htmlContent = htmlContent.replace(/const allCareers = \[[\s\S]*?\];/m, 'const allCareers = ' + newCareers + ';');
    // replace buttons
    htmlContent = htmlContent.replace(/<button class="filter-btn px-4 py-2 bg-primary text-white ledger-border text-\[12px\] font-medium transition-all" data-category="Semua">Semua<\/button>[\s\S]*?<button class="filter-btn px-4 py-2 bg-white ledger-border text-\[12px\] font-medium hover:bg-primary hover:text-white transition-all" data-category="Kesehatan">Kesehatan<\/button>/m, newFilterHTML);
    fs.writeFileSync(file05, htmlContent);
    console.log('Updated 05_pilih-cita-cita/code.html');
}

// 2. Update flexacendekia-unipdu/05_pilih-cita-cita/code.html
const file05dup = path.join(__dirname, 'flexacendekia-unipdu', '05_pilih-cita-cita', 'code.html');
if (fs.existsSync(file05dup)) {
    let htmlContent = fs.readFileSync(file05dup, 'utf8');
    htmlContent = htmlContent.replace(/const allCareers = \[[\s\S]*?\];/m, 'const allCareers = ' + newCareers + ';');
    htmlContent = htmlContent.replace(/<button class="filter-btn px-4 py-2 bg-primary text-white ledger-border text-\[12px\] font-medium transition-all" data-category="Semua">Semua<\/button>[\s\S]*?<button class="filter-btn px-4 py-2 bg-white ledger-border text-\[12px\] font-medium hover:bg-primary hover:text-white transition-all" data-category="Kesehatan">Kesehatan<\/button>/m, newFilterHTML);
    fs.writeFileSync(file05dup, htmlContent);
    console.log('Updated flexacendekia-unipdu/05_pilih-cita-cita/code.html');
}

// 3. Update flexa-career-data.js
const fileData = path.join(__dirname, 'flexa-career-data.js');
if (fs.existsSync(fileData)) {
    let jsContent = fs.readFileSync(fileData, 'utf8');
    jsContent = jsContent.replace(/const FLEXA_CAREERS = \[[\s\S]*?\];/m, 'const FLEXA_CAREERS = ' + newCareers + ';');
    jsContent = jsContent.replace(/const FLEXA_CAREER_CATEGORIES = \[[\s\S]*?\];/m, 'const FLEXA_CAREER_CATEGORIES = [\n    \'Semua\', \'Sosial & Hukum\', \'Kesehatan\', \'Pendidikan\', \'Sains & Teknologi\', \'Kreatif\', \'Bisnis\', \'Olahraga & Seni\'\n];');
    // Remove FLEXA_PROFESI_EXPLORER entirely or make it empty
    jsContent = jsContent.replace(/const FLEXA_PROFESI_EXPLORER = \[[\s\S]*?\];/m, 'const FLEXA_PROFESI_EXPLORER = []; // Section removed from 04_hasil-diagnosis');
    fs.writeFileSync(fileData, jsContent);
    console.log('Updated flexa-career-data.js');
}
